apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:
    - name: my-storage-volume
      persistentVolumeClaim:
        claimName: nginx-pvc
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: my-storage-volume
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80

